import { GatewayConfig } from '../gatewayGenerator';

export function generateMidiHandler(config: GatewayConfig): string {
  const midiConfig = config.protocols.find(p => p.type === 'midi') || config.protocols[0];
  const autoLearn = midiConfig?.settings?.autoLearn !== false;
  
  // Build variable mappings from configuration
  let variableDefinitions = '';
  
  if (midiConfig?.settings?.variables && midiConfig.settings.variables.length > 0) {
    variableDefinitions = midiConfig.settings.variables
      .map((v: any, index: number) => {
        const messageType = v.messageType || 'note_on';
        const channel = v.channel !== undefined ? v.channel : null;
        const note = v.note !== undefined ? v.note : null;
        const controller = v.controller !== undefined ? v.controller : null;
        
        return `    "${v.name}": {
      messageType: "${messageType}",
      channel: ${channel !== null ? channel : 'null'},
      note: ${note !== null ? note : 'null'},
      controller: ${controller !== null ? controller : 'null'},
      description: "${v.description || 'MIDI variable'}",
      dataType: "${v.dataType || 'int'}",
      value: 0,
      lastUpdate: null
    }${index < midiConfig.settings.variables.length - 1 ? ',' : ''}`;
      })
      .join('\n');
  }

  return `/**
 * MIDI Protocol Handler - Node.js Implementation with Python Bridge
 * Generated by Industrial Gateway Builder
 * 
 * This module uses a Python bridge with rtmidi for MIDI device connectivity.
 * The Python implementation is more reliable than Node.js native bindings
 * because it doesn't require node-gyp compilation.
 * 
 * Architecture:
 * - Node.js handler (this file) spawns Python process
 * - Python process uses rtmidi library to read MIDI devices
 * - Python outputs JSON on stdout with variable updates
 * - Node.js parses JSON and exposes via REST API
 */

const { spawn } = require('child_process');
const path = require('path');

class MidiHandler {
  constructor(config, logger) {
    this.config = config;
    this.logger = logger;
    this.enabled = config.enabled;
    this.autoLearn = ${autoLearn};
    
    // Variables storage (from config)
    this.variables = {${variableDefinitions}
    };
    
    // Python bridge process
    this.pythonProcess = null;
    this.bridgeReady = false;
    
    // Device information
    this.devices = {
      inputs: [],
      outputs: []
    };
    
    if (this.enabled) {
      this.initialize();
    }
  }

  initialize() {
    try {
      this.logger.info('🎹 Initializing MIDI Handler with Python Bridge...');
      
      // Find Python executable
      const pythonExec = this.findPythonExecutable();
      if (!pythonExec) {
        this.logger.error('Python not found. Please install Python 3.7+ and ensure it\\'s in PATH');
        this.enabled = false;
        return;
      }
      
      // Path to Python bridge script
      const bridgePath = path.join(__dirname, 'midi_bridge.py');
      
      this.logger.info(\`Starting Python MIDI bridge: \${pythonExec} \${bridgePath}\`);
      this.logger.info(\`Bridge script path: \${bridgePath}\`);
      
      // Spawn Python process
      this.pythonProcess = spawn(pythonExec, [bridgePath], {
        stdio: ['pipe', 'pipe', 'pipe'],
        shell: false
      });
      
      // Handle stdout (JSON data)
      this.pythonProcess.stdout.on('data', (data) => {
        this.handleBridgeOutput(data);
      });
      
      // Handle stderr (errors and Python tracebacks)
      let stderrBuffer = '';
      this.pythonProcess.stderr.on('data', (data) => {
        const errText = data.toString();
        stderrBuffer += errText;
        
        // Log immediately for debugging
        this.logger.error(\`MIDI Bridge stderr: \${errText}\`);
        
        // If we see a complete traceback or error, show it prominently
        if (errText.includes('Traceback') || errText.includes('Error:') || errText.includes('Exception')) {
          this.logger.error(\`⚠️  Python Error Details:\`);
          this.logger.error(stderrBuffer);
        }
      });
      
      // Handle process exit
      this.pythonProcess.on('exit', (code, signal) => {
        this.logger.warn(\`MIDI Bridge exited with code \${code}, signal \${signal}\`);
        this.enabled = false;
        this.bridgeReady = false;
      });
      
      // Handle process errors
      this.pythonProcess.on('error', (err) => {
        this.logger.error(\`Failed to start MIDI Bridge: \${err.message}\`);
        this.enabled = false;
      });
      
    } catch (error) {
      this.logger.error(\`Failed to initialize MIDI: \${error.message}\`);
      this.enabled = false;
    }
  }
  
  findPythonExecutable() {
    // Try common Python executables in order of preference
    const candidates = ['python3', 'python', 'py'];
    const { execSync } = require('child_process');
    const fs = require('fs');
    
    this.logger.info('🔍 Searching for Python with python-rtmidi...');
    
    for (const candidate of candidates) {
      try {
        // Check if Python 3 is available
        const version = execSync(\`\${candidate} --version\`, { encoding: 'utf8', stderr: 'pipe' }).trim();
        
        // Get full path
        let fullPath = '';
        try {
          if (process.platform === 'win32') {
            fullPath = execSync(\`where \${candidate}\`, { encoding: 'utf8' }).split('\\n')[0].trim();
          } else {
            fullPath = execSync(\`which \${candidate}\`, { encoding: 'utf8' }).trim();
          }
        } catch (e) {
          fullPath = candidate;
        }
        
        this.logger.info(\`  Testing: \${candidate} (\${fullPath}) - \${version}\`);
        
        if (version.includes('Python 3')) {
          // Verify rtmidi is installed
          try {
            execSync(\`\${candidate} -c "import rtmidi; print('rtmidi OK')"\`, { 
              encoding: 'utf8', 
              stdio: 'pipe' 
            });
            this.logger.info(\`✅ Selected: \${candidate} with python-rtmidi installed\`);
            return candidate;
          } catch (rtmidiErr) {
            this.logger.warn(\`⚠️  \${candidate} found but python-rtmidi is NOT installed\`);
            // Continue to next candidate
          }
        }
      } catch (err) {
        // Candidate not found, try next
        this.logger.debug(\`  \${candidate} not found in PATH\`);
      }
    }
    
    // No Python with rtmidi found
    this.logger.error('❌ No Python installation with python-rtmidi found');
    this.logger.error('   Install with: pip install python-rtmidi');
    return null;
  }
  
  handleBridgeOutput(data) {
    const lines = data.toString().split('\\n');
    
    for (const line of lines) {
      if (!line.trim()) continue;
      
      try {
        const message = JSON.parse(line);
        
        // Handle different message types
        if (message.status === 'devices_found') {
          this.devices.inputs = message.devices.map((name, index) => ({ index, name }));
          this.logger.info(\`Found \${message.devices.length} MIDI device(s)\`);
          message.devices.forEach((dev, i) => {
            this.logger.info(\`  📥 MIDI Input \${i}: \${dev}\`);
          });
        } else if (message.status === 'attempting') {
          this.logger.info(\`Attempting to connect to: \${message.device}\`);
        } else if (message.status === 'connected') {
          this.logger.info(\`✅ Connected to MIDI device: \${message.device}\${message.port !== undefined ? \` (port \${message.port})\` : ''}\`);
        } else if (message.status === 'ready') {
          this.bridgeReady = true;
          this.logger.info('✅ MIDI Bridge ready');
        } else if (message.status === 'waiting') {
          this.logger.info(\`⏳ \${message.message}\`);
          this.bridgeReady = false;
        } else if (message.status === 'scanning') {
          this.logger.info(\`🔍 \${message.message}\`);
        } else if (message.status === 'shutting_down') {
          this.logger.info('MIDI Bridge shutting down');
          this.bridgeReady = false;
        } else if (message.warning) {
          this.logger.warn(\`MIDI Bridge: \${message.warning}\`);
        } else if (message.timestamp && message.variables) {
          // Variable update message
          this.updateVariables(message.variables);
        } else if (message.error) {
          this.logger.error(\`MIDI Bridge: \${message.error}\`);
        }
      } catch (err) {
        // Not JSON, might be info message
        if (line.trim().length > 0) {
          this.logger.info(\`MIDI Bridge: \${line}\`);
        }
      }
    }
  }
  
  updateVariables(newVariables) {
    // Update configured variables
    for (const [varName, varData] of Object.entries(newVariables)) {
      if (this.variables[varName]) {
        this.variables[varName].value = varData.value;
        this.variables[varName].lastUpdate = varData.lastUpdate;
      } else if (this.autoLearn) {
        // Add learned variable
        this.variables[varName] = {
          messageType: varData.type,
          value: varData.value,
          description: varData.description,
          dataType: 'int',
          lastUpdate: varData.lastUpdate
        };
      }
    }
  }

  getVariableList() {
    return Object.keys(this.variables).map(name => ({
      name,
      ...this.variables[name]
    }));
  }

  async readVariable(variableName, device) {
    // Check configured variables
    if (this.variables[variableName]) {
      const varData = this.variables[variableName];
      return {
        value: varData.value,
        dataType: varData.dataType || 'int',
        quality: this.bridgeReady ? 'good' : 'uncertain',
        timestamp: varData.lastUpdate || new Date().toISOString()
      };
    }
    
    throw new Error(\`Variable '\${variableName}' not found\`);
  }

  async writeVariable(variableName, value, device) {
    // MIDI variables are typically read-only from device input
    throw new Error('Write operation not supported for MIDI variables');
  }

  getData(device) {
    const allVars = {};
    
    // Add all variables
    for (const [name, data] of Object.entries(this.variables)) {
      allVars[name] = data.value;
    }
    
    return allVars;
  }

  close() {
    try {
      if (this.pythonProcess) {
        this.logger.info('Closing MIDI Python bridge...');
        this.pythonProcess.kill('SIGTERM');
        this.pythonProcess = null;
        this.bridgeReady = false;
      }
    } catch (error) {
      this.logger.error(\`Error closing MIDI bridge: \${error.message}\`);
    }
  }
}

module.exports = MidiHandler;
`;
}