import { GatewayConfig } from '../gatewayGenerator';

export function generateMidiBridge(config: GatewayConfig): string {
  const midiConfig = config.protocols.find(p => p.type === 'midi') || config.protocols[0];
  const autoLearn = midiConfig?.settings?.autoLearn !== false;
  
  // Build variable configuration from the gateway config
  let variableDefinitions = '';
  
  if (midiConfig?.settings?.variables && midiConfig.settings.variables.length > 0) {
    const varDefs = midiConfig.settings.variables
      .map((v: any) => {
        const messageType = v.messageType || 'note_on';
        const channel = v.channel !== undefined ? v.channel : 'None';
        const note = v.note !== undefined ? v.note : 'None';
        const controller = v.controller !== undefined ? v.controller : 'None';
        
        return `    "${v.name}": {
        "messageType": "${messageType}",
        "channel": ${channel},
        "note": ${note},
        "controller": ${controller},
        "description": "${v.description || 'MIDI variable'}",
        "value": 0,
        "lastUpdate": None
    }`;
      })
      .join(',\n');
    
    variableDefinitions = `\n${varDefs}\n`;
  }

  return `#!/usr/bin/env python3
"""
MIDI Bridge - Python Implementation using rtmidi
Generated by Industrial Gateway Builder

This script provides MIDI device connectivity using python-rtmidi library
and exposes MIDI messages as JSON to the Node.js gateway via stdout.

Dependencies:
  pip install python-rtmidi

Why rtmidi?
- No compilation required on Windows (unlike Node.js midi module)
- More reliable cross-platform support
- Easier installation
"""

import rtmidi
import sys
import json
import time
from collections import OrderedDict

# Configuration
AUTO_LEARN = ${autoLearn ? 'True' : 'False'}
UPDATE_INTERVAL = 0.1  # seconds

# MIDI variable storage
variables = {${variableDefinitions}}

# Learned MIDI messages (for auto-learn mode)
learned_messages = {}


def get_message_type(status_byte):
    """Determine MIDI message type from status byte"""
    msg_type = (status_byte & 0xF0) >> 4
    
    type_map = {
        0x8: 'note_off',
        0x9: 'note_on',
        0xA: 'aftertouch',
        0xB: 'control_change',
        0xC: 'program_change',
        0xD: 'channel_pressure',
        0xE: 'pitchwheel'
    }
    
    return type_map.get(msg_type, 'unknown')


def get_channel(status_byte):
    """Extract channel from status byte (0-15)"""
    return status_byte & 0x0F


def get_note_name(note_number):
    """Convert MIDI note number to note name (e.g., 60 -> C4)"""
    if note_number < 0 or note_number > 127:
        return f"Note_{note_number}"
    
    notes = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
    octave = (note_number // 12) - 1
    note = notes[note_number % 12]
    return f"{note}{octave}"


def message_matches_config(msg_dict, config):
    """Check if MIDI message matches variable configuration"""
    # Check message type
    if config.get('messageType') != msg_dict['type']:
        return False
    
    # Check channel (None means any channel)
    if config.get('channel') is not None and config['channel'] != msg_dict['channel']:
        return False
    
    # Check note (for note messages)
    if 'note' in msg_dict:
        if config.get('note') is not None and config['note'] != msg_dict['note']:
            return False
    
    # Check controller (for control_change messages)
    if 'controller' in msg_dict:
        if config.get('controller') is not None and config['controller'] != msg_dict['controller']:
            return False
    
    return True


def handle_midi_message(message, data=None):
    """Process incoming MIDI message"""
    try:
        status, data1, data2 = message[0][:3]
        
        msg_type = get_message_type(status)
        channel = get_channel(status)
        
        # Build message dict
        msg_dict = {
            'type': msg_type,
            'channel': channel,
            'value': data2
        }
        
        # Add specific fields based on message type
        if msg_type in ['note_on', 'note_off', 'aftertouch']:
            msg_dict['note'] = data1
            msg_dict['velocity'] = data2
        elif msg_type == 'control_change':
            msg_dict['controller'] = data1
            msg_dict['value'] = data2
        elif msg_type == 'program_change':
            msg_dict['program'] = data1
        elif msg_type == 'pitchwheel':
            # Combine data1 and data2 for 14-bit pitch wheel value
            msg_dict['value'] = (data2 << 7) | data1
        
        # Update configured variables
        updated = False
        for var_name, var_config in variables.items():
            if message_matches_config(msg_dict, var_config):
                variables[var_name]['value'] = msg_dict['value']
                variables[var_name]['lastUpdate'] = time.time()
                updated = True
        
        # Auto-learn new messages
        if AUTO_LEARN and not updated:
            # Generate unique key for this message
            key_parts = [msg_dict['type'], str(msg_dict['channel'])]
            
            if 'note' in msg_dict:
                key_parts.append(get_note_name(msg_dict['note']))
            elif 'controller' in msg_dict:
                key_parts.append(f"CC{msg_dict['controller']}")
            
            key = '_'.join(key_parts)
            
            # Store or update learned message
            if key not in learned_messages:
                learned_messages[key] = {
                    'name': key,
                    'type': msg_dict['type'],
                    'channel': msg_dict['channel'],
                    'value': msg_dict['value'],
                    'lastUpdate': time.time()
                }
                if 'note' in msg_dict:
                    learned_messages[key]['note'] = msg_dict['note']
                if 'controller' in msg_dict:
                    learned_messages[key]['controller'] = msg_dict['controller']
            else:
                learned_messages[key]['value'] = msg_dict['value']
                learned_messages[key]['lastUpdate'] = time.time()
        
    except Exception as e:
        print(json.dumps({'error': f'MIDI message parsing error: {str(e)}'}), flush=True)


def get_available_ports():
    """Get list of available MIDI ports"""
    try:
        temp_midi = rtmidi.MidiIn()
        ports = temp_midi.get_ports()
        del temp_midi
        return ports
    except:
        return []


def setup_midi():
    """Initialize MIDI input - tries all available ports"""
    try:
        midiin = rtmidi.MidiIn()
        ports = midiin.get_ports()
        
        if len(ports) == 0:
            print(json.dumps({'warning': 'No MIDI devices found. Waiting for device...'}), flush=True)
            return None, None, None
        
        # Print available devices
        print(json.dumps({
            'status': 'devices_found',
            'devices': ports
        }), flush=True)
        
        # Try each port until one works
        for port_index in range(len(ports)):
            port_name = ports[port_index]
            
            try:
                print(json.dumps({'status': 'attempting', 'device': port_name, 'port': port_index}), flush=True)
                
                # Create fresh MidiIn for each attempt
                if port_index > 0:
                    midiin = rtmidi.MidiIn()
                    
                midiin.open_port(port_index)
                midiin.set_callback(handle_midi_message)
                
                print(json.dumps({
                    'status': 'connected',
                    'device': port_name,
                    'port': port_index
                }), flush=True)
                
                return midiin, port_name, port_index
                
            except Exception as port_error:
                print(json.dumps({
                    'warning': f'Could not open port {port_index} ({port_name}): {str(port_error)}'
                }), flush=True)
                # Continue to next port
        
        # If we got here, no ports could be opened
        print(json.dumps({
            'warning': 'Could not open any MIDI device. All devices may be in use.'
        }), flush=True)
        return None, None, None
        
    except Exception as e:
        print(json.dumps({'error': f'MIDI setup error: {str(e)}'}), flush=True)
        return None, None, None


def get_all_variables():
    """Get all variables (configured + learned) as dict"""
    all_vars = {}
    
    # Add configured variables
    for var_name, var_data in variables.items():
        all_vars[var_name] = {
            'value': var_data['value'],
            'type': var_data['messageType'],
            'description': var_data.get('description', ''),
            'lastUpdate': var_data.get('lastUpdate')
        }
    
    # Add learned messages
    for key, learned_data in learned_messages.items():
        all_vars[key] = {
            'value': learned_data['value'],
            'type': learned_data['type'],
            'description': f"Auto-learned: {learned_data['type']}",
            'lastUpdate': learned_data.get('lastUpdate')
        }
    
    return all_vars


def main():
    """Main loop with device scanning and auto-reconnection"""
    midiin = None
    current_device = None
    current_port = None
    last_scan_time = 0
    scan_interval = 5.0  # Scan for new devices every 5 seconds
    
    # Initial connection attempt
    midiin, current_device, current_port = setup_midi()
    
    if midiin is not None:
        print(json.dumps({'status': 'ready'}), flush=True)
    else:
        print(json.dumps({'status': 'waiting', 'message': 'Waiting for MIDI device...'}), flush=True)
    
    try:
        while True:
            current_time = time.time()
            
            # Periodic device scanning to detect new devices or reconnect
            if current_time - last_scan_time >= scan_interval:
                last_scan_time = current_time
                
                # Check if we need to reconnect
                if midiin is None:
                    print(json.dumps({'status': 'scanning', 'message': 'Scanning for MIDI devices...'}), flush=True)
                    midiin, current_device, current_port = setup_midi()
                    
                    if midiin is not None:
                        print(json.dumps({'status': 'ready'}), flush=True)
                else:
                    # Verify current connection is still valid
                    try:
                        # Try to check if port is still open by checking ports list
                        available_ports = get_available_ports()
                        
                        # If our device disappeared and we're not using virtual port
                        if current_device != 'virtual' and current_port is not None:
                            if current_port >= len(available_ports) or (len(available_ports) > 0 and current_device not in available_ports):
                                print(json.dumps({'warning': f'Device {current_device} disconnected. Attempting to reconnect...'}), flush=True)
                                try:
                                    midiin.close_port()
                                except:
                                    pass
                                midiin = None
                                current_device = None
                                current_port = None
                    except:
                        pass
            
            time.sleep(UPDATE_INTERVAL)
            
            # Output current variable state only if connected
            if midiin is not None:
                output = {
                    'timestamp': time.time(),
                    'variables': get_all_variables()
                }
                print(json.dumps(output), flush=True)
            
    except KeyboardInterrupt:
        print(json.dumps({'status': 'shutting_down'}), flush=True)
    finally:
        if midiin:
            try:
                midiin.close_port()
            except:
                pass
            print(json.dumps({'status': 'closed'}), flush=True)


if __name__ == '__main__':
    main()
`;
}
