import { GatewayConfig } from '../gatewayGenerator';

export function generatePythonModbusServer(config: GatewayConfig): string {
  const modbusConfig = config.protocols.find(p => p.type === 'modbus-tcp') || config.protocols[0];
  const serverPort = modbusConfig?.settings?.serverPort || 502;
  const syncPort = 9999;

  // Build variable mappings from configuration
  let holdingRegisterVars = '';
  let coilVars = '';
  
  if (modbusConfig?.settings?.registerMap) {
    const registerMap = modbusConfig.settings.registerMap;
    
    if (registerMap.holdingRegisters?.variables && registerMap.holdingRegisters.variables.length > 0) {
      holdingRegisterVars = registerMap.holdingRegisters.variables
        .map((v, index, array) => {
          const isLast = index === array.length - 1;
          const comma = isLast ? '' : ',';
          return `    "${v.name}": ${v.address}${comma}  # ${(v.description || 'No description').replace(/,/g, '')}`;
        })
        .join('\n');
    }
    
    if (registerMap.coils?.variables && registerMap.coils.variables.length > 0) {
      coilVars = registerMap.coils.variables
        .map((v, index, array) => {
          const isLast = index === array.length - 1;
          const comma = isLast ? '' : ',';
          return `    "${v.name}": ${v.address}${comma}  # ${(v.description || 'No description').replace(/,/g, '')}`;
        })
        .join('\n');
    }
  }

  return `#!/usr/bin/env python3
"""
Python Modbus TCP Server
Generated by Industrial Gateway Builder

This server provides Modbus TCP functionality using pymodbus library.
It maintains synchronization with the Node.js REST API via TCP socket.
"""

import asyncio
import socket
import json
import logging
import sys
from collections import OrderedDict
from pymodbus.server import StartAsyncTcpServer
from pymodbus.datastore import (
    ModbusServerContext,
    ModbusSequentialDataBlock,
)
# Import device context (replaces ModbusSlaveContext in pymodbus 3.x)
try:
    from pymodbus.datastore import ModbusSlaveContext
except ImportError:
    # For pymodbus 3.x, use ModbusDeviceContext
    from pymodbus.datastore import ModbusDeviceContext as ModbusSlaveContext

# Import framer for TCP connections
try:
    from pymodbus.framer.socket_framer import ModbusSocketFramer as ModbusTcpFramer
except ImportError:
    try:
        from pymodbus.framer import ModbusTcpFramer
    except ImportError:
        # For older versions, no explicit framer needed for TCP
        ModbusTcpFramer = None

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Variable mappings from configuration  
HOLDING_REGISTER_MAP = {
${holdingRegisterVars}
}

COIL_MAP = {
${coilVars}
}

class CustomDataBlock(ModbusSequentialDataBlock):
    """Custom data block with change notifications"""
    
    def __init__(self, address, values, notify_callback=None):
        super().__init__(address, values)
        self.notify_callback = notify_callback
    
    def setValues(self, address, values):
        """Override to notify of changes"""
        old_values = self.getValues(address, len(values))
        super().setValues(address, values)
        
        if self.notify_callback and old_values != values:
            # Notify of changes
            for i, (old_val, new_val) in enumerate(zip(old_values, values)):
                if old_val != new_val:
                    self.notify_callback(address + i, new_val)

class ModbusDataStore:
    """Manages Modbus data and synchronization"""
    
    def __init__(self):
        self.sync_clients = []
        self.server_context = None
        self.setup_datastore()
    
    def setup_datastore(self):
        """Initialize Modbus data blocks"""
        # Initialize data blocks
        self.holding_registers = CustomDataBlock(0, [0] * 65536, self.on_holding_register_change)
        self.input_registers = CustomDataBlock(0, [0] * 65536)
        self.coils = CustomDataBlock(0, [False] * 65536, self.on_coil_change)
        self.discrete_inputs = CustomDataBlock(0, [False] * 65536)
        
        # Create slave context (device context in pymodbus 3.x)
        slave_context = ModbusSlaveContext(
            di=self.discrete_inputs,
            co=self.coils,
            hr=self.holding_registers,
            ir=self.input_registers
        )
        
        # Create server context (devices parameter in pymodbus 3.x)
        self.server_context = ModbusServerContext(devices=slave_context, single=True)
        
        logger.info(f"🐍 Modbus datastore initialized")
        logger.info(f"📊 Holding registers: {len(HOLDING_REGISTER_MAP)} variables")
        logger.info(f"📊 Coils: {len(COIL_MAP)} variables")
    
    def on_holding_register_change(self, address, value):
        """Handle holding register changes"""
        var_name = self.get_variable_name(HOLDING_REGISTER_MAP, address)
        if var_name:
            logger.info(f"📝 Holding register {address} ({var_name}) changed to {value}")
            self.notify_sync_clients('holdingRegister', address, value, var_name)
    
    def on_coil_change(self, address, value):
        """Handle coil changes"""
        var_name = self.get_variable_name(COIL_MAP, address)
        if var_name:
            logger.info(f"📝 Coil {address} ({var_name}) changed to {value}")
            self.notify_sync_clients('coil', address, value, var_name)
    
    def get_variable_name(self, var_map, address):
        """Get variable name by address"""
        for name, addr in var_map.items():
            if addr == address:
                return name
        return None
    
    def notify_sync_clients(self, register_type, address, value, var_name):
        """Notify connected sync clients of changes"""
        message = {
            'type': 'register_update',
            'registerType': register_type,
            'address': address,
            'value': value,
            'variableName': var_name,
            'timestamp': asyncio.get_event_loop().time()
        }
        
        # Send to all connected sync clients
        disconnected_clients = []
        for client in self.sync_clients:
            try:
                data = json.dumps(message).encode('utf-8')
                client.write(data)
            except Exception as e:
                logger.error(f"Failed to notify sync client: {e}")
                disconnected_clients.append(client)
        
        # Remove disconnected clients
        for client in disconnected_clients:
            self.sync_clients.remove(client)
    
    def write_variable(self, register_type, address, value):
        """Write value to variable"""
        try:
            if register_type == 'holdingRegister':
                self.server_context[0].setValues(3, address, [value])
                logger.info(f"✅ Written holding register {address} = {value}")
            elif register_type == 'coil':
                self.server_context[0].setValues(1, address, [value])
                logger.info(f"✅ Written coil {address} = {value}")
            else:
                logger.error(f"❌ Unsupported register type: {register_type}")
        except Exception as e:
            logger.error(f"❌ Failed to write {register_type} {address}: {e}")

# Global data store instance
datastore = ModbusDataStore()

async def handle_sync_client(reader, writer):
    """Handle synchronization client connections"""
    addr = writer.get_extra_info('peername')
    logger.info(f"🔗 Sync client connected from {addr}")
    
    datastore.sync_clients.append(writer)
    
    try:
        while True:
            data = await reader.read(1024)
            if not data:
                break
                
            try:
                # Split by newlines in case multiple messages arrived in one read
                raw = data.decode('utf-8').strip()
                messages = [line for line in raw.split('\\n') if line.strip()]
                
                for msg_str in messages:
                    try:
                        message = json.loads(msg_str)
                        
                        if message['type'] == 'write_variable':
                            register_type = message['registerType']
                            address = message['address']
                            value = message['value']
                            
                            logger.info(f"📝 Received write request: {register_type}[{address}] = {value}")
                            datastore.write_variable(register_type, address, value)
                            
                    except json.JSONDecodeError as e:
                        logger.error(f"❌ Invalid JSON from sync client: {e}")
                    except KeyError as e:
                        logger.error(f"❌ Missing field in sync message: {e}")
            except Exception as e:
                logger.error(f"❌ Error processing sync message: {e}")
                
    except asyncio.CancelledError:
        pass
    except Exception as e:
        logger.error(f"❌ Sync client error: {e}")
    finally:
        if writer in datastore.sync_clients:
            datastore.sync_clients.remove(writer)
        writer.close()
        await writer.wait_closed()
        logger.info(f"🔗 Sync client {addr} disconnected")

async def start_sync_server():
    """Start the synchronization server for Node.js communication"""
    server = await asyncio.start_server(
        handle_sync_client, 
        '127.0.0.1', 
        ${syncPort},
        reuse_address=True
    )
    
    addr = server.sockets[0].getsockname()
    logger.info(f"🔗 Sync server started on {addr[0]}:{addr[1]}")
    
    async with server:
        await server.serve_forever()

async def start_modbus_server():
    """Start the Modbus TCP server"""
    try:
        # Get local IP for display
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        local_ip = s.getsockname()[0]
        s.close()
        
        logger.info(f"🚀 Starting Modbus TCP server...")
        logger.info(f"🌐 Server will be accessible at {local_ip}:${serverPort}")
        
        # Start the server (TCP doesn't need explicit framer in modern pymodbus)
        if ModbusTcpFramer:
            await StartAsyncTcpServer(
                context=datastore.server_context,
                address=("0.0.0.0", ${serverPort}),
                framer=ModbusTcpFramer
            )
        else:
            # For newer pymodbus versions, framer is auto-detected
            await StartAsyncTcpServer(
                context=datastore.server_context,
                address=("0.0.0.0", ${serverPort})
            )
        
    except Exception as e:
        logger.error(f"❌ Failed to start Modbus server: {e}")
        raise

async def main():
    """Main application entry point"""
    logger.info("🐍 Python Modbus Server Starting...")
    logger.info(f"📊 Configuration Summary:")
    logger.info(f"   • Modbus TCP Port: ${serverPort}")
    logger.info(f"   • Sync Port: ${syncPort}")
    logger.info(f"   • Holding Registers: {len(HOLDING_REGISTER_MAP)}")
    logger.info(f"   • Coils: {len(COIL_MAP)}")
    
    try:
        # Start both servers concurrently
        await asyncio.gather(
            start_modbus_server(),
            start_sync_server()
        )
    except KeyboardInterrupt:
        logger.info("🔌 Server shutdown requested")
    except Exception as e:
        logger.error(f"❌ Server error: {e}")
        raise

if __name__ == "__main__":
    try:
        if len(sys.argv) > 1:
            # Port provided as command line argument
            port = int(sys.argv[1])
            logger.info(f"🔧 Using port from command line: {port}")
        
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("🔌 Shutting down...")
    except Exception as e:
        logger.error(f"❌ Fatal error: {e}")
        sys.exit(1)
`;
}

export function generateModbusProxy(config: GatewayConfig): string {
  return `const net = require('net');

class ModbusHandler {
  constructor(protocolConfig, logger) {
    this.config = protocolConfig;
    this.logger = logger;
    this.variableMap = new Map();
    this.registerData = new Map();
    this.pythonProcess = null;
    this.tcpClient = null;
    
    this.logger.info('🐍 Initializing Python-based Modbus Handler...');
    this.initialize().catch(err => {
      this.logger.error('Failed to initialize ModbusHandler:', err);
    });
  }

  async initialize() {
    if (!this.config.enabled) {
      this.logger.info('🚫 Modbus protocol is disabled');
      return true;
    }

    try {
      this.logger.info('🚀 Initializing Python Modbus protocol handler...');
      
      // Initialize variables
      await this.initializeVariables();
      
      if (this.config.mode === 'server') {
        await this.startPythonModbusServer();
        await this.connectToModbusServer();
      }

      this.logger.info('✅ Python Modbus protocol handler initialized successfully');
      return true;

    } catch (error) {
      this.logger.error('❌ Failed to initialize Python Modbus protocol handler:', error);
      return false;
    }
  }

  async initializeVariables() {
    const registerMap = this.config.settings?.registerMap;
    
    if (!registerMap) {
      this.logger.warn('⚠️ No register map found - using empty configuration');
      return;
    }
    
    this.logger.info('📝 Initializing variables from configuration...');
    
    let totalVariables = 0;
    
    // Process holding registers
    if (registerMap.holdingRegisters?.variables) {
      registerMap.holdingRegisters.variables.forEach(variable => {
        if (variable.name && variable.address !== undefined) {
          this.variableMap.set(variable.name, {
            type: 'holdingRegister',
            address: variable.address,
            dataType: variable.dataType || 'int16'
          });
          this.registerData.set(variable.name, { 
            value: 0, 
            quality: 'good', 
            timestamp: new Date().toISOString()
          });
          totalVariables++;
        }
      });
    }
    
    // Process coils
    if (registerMap.coils?.variables) {
      registerMap.coils.variables.forEach(variable => {
        if (variable.name && variable.address !== undefined) {
          this.variableMap.set(variable.name, {
            type: 'coil',
            address: variable.address,
            dataType: 'boolean'
          });
          this.registerData.set(variable.name, { 
            value: false, 
            quality: 'good', 
            timestamp: new Date().toISOString()
          });
          totalVariables++;
        }
      });
    }
    
    this.logger.info(\`✅ Initialized \${totalVariables} variables\`);
  }

  async startPythonModbusServer() {
    const { spawn } = require('child_process');
    const path = require('path');
    
    const serverPort = this.config.settings?.serverPort || 502;
    const pythonScript = path.join(__dirname, '../protocols/modbus_server.py');
    
    this.logger.info(\`🐍 Starting Python Modbus server on port \${serverPort}...\`);
    
    // Start Python Modbus server
    this.pythonProcess = spawn('python', [pythonScript, serverPort.toString()], {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env, PYTHONUNBUFFERED: '1' }
    });
    
    this.pythonProcess.stdout.on('data', (data) => {
      const output = data.toString().trim();
      if (output) {
        this.logger.info(\`🐍 Python Server: \${output}\`);
      }
    });
    
    this.pythonProcess.stderr.on('data', (data) => {
      const text = data.toString().trim();
      if (text) {
        // Python logging goes to stderr by default - only treat as error if it actually is one
        const isError = /ERROR|CRITICAL|Traceback|SyntaxError|Exception/.test(text);
        if (isError) {
          this.logger.error(\`🐍 Python: \${text}\`);
        } else {
          this.logger.info(\`🐍 Python: \${text}\`);
        }
      }
    });
    
    this.pythonProcess.on('exit', (code) => {
      this.logger.warn(\`🐍 Python Modbus server exited with code \${code}\`);
    });
    
    // Wait for server to start
    await new Promise(resolve => setTimeout(resolve, 3000));
    this.logger.info('✅ Python Modbus server started');
  }

  async connectToModbusServer() {
    const syncPort = 9999; // Port for syncing with Python server
    
    this.logger.info(\`🔗 Connecting to Python server sync port \${syncPort}...\`);
    
    this.tcpClient = new net.Socket();
    
    return new Promise((resolve, reject) => {
      this.tcpClient.connect(syncPort, '127.0.0.1', () => {
        this.logger.info('✅ Connected to Python Modbus server sync port');
        resolve(true);
      });
      
      this.tcpClient.on('error', (err) => {
        this.logger.error('❌ Failed to connect to Python server:', err.message);
        reject(err);
      });
      
      this.tcpClient.on('data', (data) => {
        try {
          const message = JSON.parse(data.toString());
          this.handleServerMessage(message);
        } catch (err) {
          this.logger.error('❌ Failed to parse server message:', err.message);
        }
      });
    });
  }

  handleServerMessage(message) {
    if (message.type === 'register_update') {
      // Update local variable cache when Python server registers change
      const { registerType, address, value, variableName } = message;
      
      if (variableName && this.variableMap.has(variableName)) {
        this.registerData.set(variableName, {
          value: value,
          quality: 'good',
          timestamp: new Date().toISOString()
        });
        this.logger.debug(\`🔄 Updated \${variableName} = \${value}\`);
      }
    }
  }

  async writeVariable(variableName, value) {
    try {
      if (!this.variableMap.has(variableName)) {
        throw new Error(\`Variable '\${variableName}' not found\`);
      }

      const config = this.variableMap.get(variableName);
      
      // Send update to Python server
      if (this.tcpClient && this.tcpClient.readyState === 'open') {
        const message = {
          type: 'write_variable',
          registerType: config.type,
          address: config.address,
          value: value
        };
        
        this.tcpClient.write(JSON.stringify(message) + '\\n');
        
        // Update local cache
        this.registerData.set(variableName, {
          value: value,
          quality: 'good',
          timestamp: new Date().toISOString()
        });
        
        this.logger.info(\`📝 Written \${variableName} = \${value}\`);
        return { success: true, message: \`Successfully wrote \${value} to \${variableName}\` };
      } else {
        throw new Error('Not connected to Python server');
      }
      
    } catch (error) {
      this.logger.error(\`Write variable error: \${error.message}\`);
      return { success: false, message: error.message };
    }
  }

  async readVariable(variableName) {
    const config = this.variableMap.get(variableName);
    const data = this.registerData.get(variableName);
    
    if (!config) {
      return {
        value: null,
        dataType: 'unknown',
        quality: 'bad',
        timestamp: new Date().toISOString()
      };
    }
    
    return {
      value: data?.value || null,
      dataType: config.dataType || 'unknown',
      quality: data?.quality || 'good',
      timestamp: data?.timestamp || new Date().toISOString()
    };
  }

  getVariableList() {
    return Array.from(this.variableMap.keys());
  }

  getVariableInfo(variableName) {
    const config = this.variableMap.get(variableName);
    const data = this.registerData.get(variableName);
    
    if (!config) return null;
    
    return {
      name: variableName,
      type: config.type,
      address: config.address,
      dataType: config.dataType,
      value: data?.value,
      quality: data?.quality || 'unknown',
      timestamp: data?.timestamp
    };
  }

  async shutdown() {
    this.logger.info('🔌 Shutting down ModbusHandler...');
    
    if (this.tcpClient) {
      this.tcpClient.destroy();
    }
    
    if (this.pythonProcess) {
      this.pythonProcess.kill();
    }
    
    this.logger.info('✅ ModbusHandler shutdown complete');
  }
}

module.exports = ModbusHandler;
`;
}

export function generatePythonRequirements(config: GatewayConfig): string {
  const hasModbus = config.protocols.some(p => p.type.includes('modbus') && p.enabled);
  const hasMqtt = config.protocols.some(p => p.type === 'mqtt' && p.enabled);
  const hasMidi = config.protocols.some(p => p.type === 'midi' && p.enabled);
  
  let requirements = `# Python requirements for gateway protocols\n`;

  if (hasModbus) {
    requirements += `pymodbus>=3.0.0\n`;
  }
  
  if (hasMqtt) {
    requirements += `asyncio-mqtt>=0.11.0\n`;
  }

  if (hasMidi) {
    requirements += `python-rtmidi>=1.5.0\n`;
  }
  
  if (!hasModbus && !hasMqtt && !hasMidi) {
    requirements += `# No Python dependencies required\n`;
  }

  return requirements;
}

export function generateModbusStarter(config: GatewayConfig): string {
  return `#!/usr/bin/env python3
"""
Standalone Python Modbus Server Starter
This script can be run independently for testing
"""

import sys
import os

# Add current directory to path to import modbus_server
sys.path.insert(0, os.path.dirname(__file__))

if __name__ == "__main__":
    try:
        # Import and run the modbus server
        import modbus_server
        modbus_server.main()
    except ImportError as e:
        print(f"Error importing modbus_server: {e}")
        print("Make sure modbus_server.py is in the same directory")
        sys.exit(1)
    except Exception as e:
        print(f"Error starting Modbus server: {e}")
        sys.exit(1)
`;
}